### ISSUE TITLE
This mod doesn't work

### ISSUE THREAD

**Issue by Jerome226** [Quarris/ChoppingBlock#1]
I don't need to explain this further, i'm using the 1.18.2 version and i just cant right click with a log to place it, i can only do it with a hopper.
And when the item is in i cant get the output item, would like to know what im doing wrong.

**Comment by Jerome226** [comment]
Nevermind, my mistake sorry

**Comment by Quarris** [comment]
That's alright. I would kindly ask to refrain from saying things like "I don't need to explain this further" for any mod, since if there was in fact a bug with the mod we would really like to know what exactly doesn't work :P
